# -*- coding: utf-8 -*-
"""app_gmm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wD_s_qcecNWmO64wZB35vHSqPC32evd
"""

# app_ir_withchanges.py
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(
    page_title="IDEC Research Paper Clustering",
    page_icon="📘",
    layout="wide"
)

# Title
st.title("Research Paper Clustering Using IDEC + GMM")
st.markdown("""
### Deep Embedded Clustering with GMM for arXiv Papers
This application uses IDEC (Improved Deep Embedded Clustering) and Gaussian Mixture Model to group arXiv research papers into semantic topics.
""")

# Load Data
try:
    df = pd.read_csv("arxiv_abstracts_new_new.csv")
    st.success("Data loaded successfully.")
except FileNotFoundError:
    st.error("'arxiv_abstracts_new.csv' not found. Please run the deep clustering pipeline first.")
    st.stop()

required_cols = ['title', 'authors', 'abstract', 'clean_abstract', 'cluster', 'cluster_topic']
if any(c not in df.columns for c in required_cols):
    st.error("Missing required columns. Please regenerate the dataset.")
    st.stop()

# Sidebar: Cluster Explorer
st.sidebar.markdown("## Cluster Explorer")
n_clusters = len(df["cluster"].unique())
cluster_ids = sorted(df["cluster"].unique())
selected_cluster = st.sidebar.selectbox("Select Cluster ID:", cluster_ids)

cluster_data = df[df["cluster"] == selected_cluster]
if len(cluster_data) == 0:
    st.sidebar.warning("This cluster contains no papers.")
    st.stop()

topic = cluster_data["cluster_topic"].iloc[0]
num_papers = len(cluster_data)

st.sidebar.markdown(f"**Cluster Topic:** `{topic}`")
st.sidebar.markdown(f"**Number of Papers:** `{num_papers}`")

# Main: Show Clustered Papers
st.markdown(f"## Cluster ID: {selected_cluster}  |  Topic: {topic}")
if num_papers > 0:
    for i, row in cluster_data.iterrows():
        st.markdown(f"---\n### {row['title']}\n*Authors:* {row['authors']}\n\n*Abstract:* {row['abstract']}")
else:
    st.warning("No papers found for this cluster.")

# Optional: Cluster Paper Counts Visual
st.markdown("## Cluster Distribution")
fig, ax = plt.subplots(figsize=(8,3))
cluster_counts = df["cluster"].value_counts().sort_index()
ax.bar(range(n_clusters), cluster_counts)
ax.set_xlabel("Cluster ID")
ax.set_ylabel("Number of Papers")
ax.set_title("Number of Papers in Each Cluster")
st.pyplot(fig)

# Optional: Download Button for Cluster Papers
csv = cluster_data.to_csv(index=False)
st.download_button(
    label="Download Cluster Papers as CSV",
    data=csv,
    file_name=f"cluster_{selected_cluster}_papers.csv",
    mime='text/csv'
)